name: CI Check
run-name: ci
on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.29
      - run: bun install
      - run: bun run lint
      - run: bun run format
      - run: bun run cdktf list
      - run: bun run cdktf synth